name: Nextflow Pipeline 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up JDK 
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        
    - name: Run pipeline
      env:
        NXF_VER: 23.10.1  
      run: |  
        nextflow run main.nf -resume

    - name: Generate test data
      run: python generate_test_data.py
        
  test:

    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2

    - name: Activate conda env
      run: |
        conda activate bio
    
    - name: Test pipeline results
      run: |
        # Add test steps here
        pytest tests/test.py