name: Cas12 Nextflow Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: zulu

      - name: Install Nextflow
        run: |
          curl -fsSL https://get.nextflow.io | bash
          mkdir -p $HOME/.local/bin
          mv nextflow $HOME/.local/bin

      - name: Add Nextflow to path
        run: |
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Run pipeline
        env:
          NXF_VER: 23.10.1
        run: |
          cd $GITHUB_WORKSPACE  # Change to the root of your GitHub repository
          nextflow run main.nf

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in the repository
        run: ls -la

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bio
          environment-file: envs/environment.yml
          python-version: 3.9
          auto-activate-base: false

      - name: Install pytest and test pipeline results
        run: |
          conda install -c conda-forge pytest
          echo "source activate bio" >> $GITHUB_ENV
          pytest tests/test.py
        shell: bash -l {0}