name: Cas12 Nextflow Pipeline 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up JDK 
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: zulu
        
    - name: Install Nextflow
      uses: actions/setup-command@v3
      with: 
        command: nextflow
        url: https://github.com/nextflow-io/nextflow/releases/download/v23.10.1/nextflow
        destination: ~/.local/bin

    - name: Add Nextflow to PATH
      run: |
        echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
        source ~/.bashrc

    - name: Run pipeline
      env:
        NXF_VER: 23.10.1
      run: |  
        nextflow run /Users/jamessacco/Github/projs/cas12/src/pipelines/main.nf

  test:

    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2

    - name: Activate conda env
      run: |
        conda activate bio
    
    - name: Test pipeline results
      run: |
        # Add test steps here
        pytest tests/test.py