name: Cas12 Nextflow Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: zulu

      - name: Install Nextflow
        run: |
          curl -fsSL https://get.nextflow.io | bash
          mkdir -p $HOME/bin
          mv nextflow $HOME/bin

      - name: Add Nextflow to path
        run: |
          echo 'export PATH="$HOME/bin:$PATH"' >> $HOME/.bash_profile
          source $HOME/.bash_profile

      - name: Run pipeline
        env:
          NXF_VER: 23.10.1
        run: |
          nextflow run /Users/jamessacco/Github/projs/cas12/src/pipelines/main.nf

  test:

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Activate conda env
        run: |
          . $HOME/miniconda/etc/profile.d/conda.sh
          conda activate bio

      - name: Test pipeline results
        run: |
          # Add test steps here
          pytest tests/test.py
