name: Cas12 Nextflow Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: zulu

      - name: Install Nextflow
        run: |
          curl -fsSL https://get.nextflow.io | bash
          mkdir -p $HOME/.local/bin
          mv nextflow $HOME/.local/bin

      - name: Add Nextflow to path
        run: |
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Run pipeline
        env:
          NXF_VER: 23.10.1
        run: |
          cd $GITHUB_WORKSPACE  # Change to the root of your GitHub repository
          nextflow run main.nf

test:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - name: Activate conda env
      run: |
        source /opt/conda/etc/profile.d/conda.sh  # Update the path to conda.sh
        conda activate bio

    - name: Test pipeline results
      run: |
        # Add test steps here
        pytest tests/test.py